version: 2.0
jobs:
  build_and_test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test
          command: |
            gradle test
      - store_test_results:
          path: build/test-results
      - run:
          name: Build
          command: |
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: jar-files
  package_and_publish:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: |
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: jar-files
workflows:
  version: 2
  awesome_pipeline:
    jobs:
      - build_and_test
      - package_and_publish:
          requires:
            - build_and_test
