version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Test
          command: |
            gradle test
      - store_test_results:
          path: build/test-results
      - run:
          name: Build
          command: |
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: jar-files
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: |
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: jar-files
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - build
